package com.mojang.minecraftpe.demo;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int bg32 = 0x7f020000;
        public static final int bgtiled = 0x7f020001;
        public static final int btn_nw_cancel = 0x7f020002;
        public static final int btn_nw_create = 0x7f020003;
        public static final int btngamemode = 0x7f020004;
        public static final int cancel_0_1 = 0x7f020005;
        public static final int cancel_0_3 = 0x7f020006;
        public static final int cancel_1_1 = 0x7f020007;
        public static final int cancel_1_3 = 0x7f020008;
        public static final int create_0_1 = 0x7f020009;
        public static final int create_0_3 = 0x7f02000a;
        public static final int create_1_1 = 0x7f02000b;
        public static final int create_1_3 = 0x7f02000c;
        public static final int creative_3 = 0x7f02000d;
        public static final int icon = 0x7f02000e;
        public static final int icon_demo = 0x7f02000f;
        public static final int iconx = 0x7f020010;
        public static final int survival_3 = 0x7f020011;
        public static final int worldname = 0x7f020012;
        public static final int worldname_3 = 0x7f020013;
    }

    public static final class layout {
        public static final int create_new_world = 0x7f030000;
        public static final int create_world_screen = 0x7f030001;
        public static final int main = 0x7f030002;
        public static final int mainmenu_options = 0x7f030003;
        public static final int rename_mp_world = 0x7f030004;
    }

    public static final class xml {
        public static final int preferences = 0x7f040000;
    }

    public static final class string {
        public static final int app_name = 0x7f050000;
        public static final int app_name_demo = 0x7f050001;
        public static final int xperiaplayoptimized_content = 0x7f050002;
        public static final int app_name_short = 0x7f050003;
        public static final int app_name_short_demo = 0x7f050004;
        public static final int createworld_name = 0x7f050005;
        public static final int createworld_new_world = 0x7f050006;
        public static final int createworld_seed = 0x7f050007;
        public static final int createworld_seed_info = 0x7f050008;
        public static final int gamemode_survival_summary = 0x7f050009;
        public static final int gamemode_creative_summary = 0x7f05000a;
        public static final int renameworld_title = 0x7f05000b;
        public static final int renameworld_saved_world = 0x7f05000c;
        public static final int mmoptions_mp_username_title = 0x7f05000d;
        public static final int mmoptions_mp_username_dialog = 0x7f05000e;
        public static final int mmoptions_mp_server_visible_default_title = 0x7f05000f;
        public static final int mmoptions_ctrl_sensitivity_title = 0x7f050010;
        public static final int mmoptions_ctrl_invertmouse_title = 0x7f050011;
        public static final int mmoptions_ctrl_islefthanded_title = 0x7f050012;
        public static final int mmoptions_ctrl_usetouchscreen_title = 0x7f050013;
        public static final int mmoptions_ctrl_usetouchjoypad_title = 0x7f050014;
        public static final int mmoptions_feedback_vibration_title = 0x7f050015;
        public static final int mmoptions_feedback_vibration_summary = 0x7f050016;
        public static final int mmoptions_gfx_fancygraphics_title = 0x7f050017;
        public static final int mmoptions_gfx_fancygraphics_summary = 0x7f050018;
        public static final int mmoptions_gfx_fancygraphics_summary_powervr = 0x7f050019;
        public static final int mmoptions_gfx_lowquality_title = 0x7f05001a;
        public static final int mmoptions_gfx_lowquality_summary = 0x7f05001b;
    }

    public static final class id {
        public static final int linearLayout2 = 0x7f060000;
        public static final int linearLayout1 = 0x7f060001;
        public static final int button_createworld_cancel = 0x7f060002;
        public static final int header_createworld_worldname = 0x7f060003;
        public static final int button_createworld_create = 0x7f060004;
        public static final int linearLayout3 = 0x7f060005;
        public static final int View01 = 0x7f060006;
        public static final int editText_worldName = 0x7f060007;
        public static final int view1 = 0x7f060008;
        public static final int linearLayout4 = 0x7f060009;
        public static final int button_gameMode = 0x7f06000a;
        public static final int linearLayout5 = 0x7f06000b;
        public static final int labelGameModeDesc = 0x7f06000c;
        public static final int linearLayout6 = 0x7f06000d;
        public static final int textView2 = 0x7f06000e;
        public static final int linearLayout7 = 0x7f06000f;
        public static final int View03 = 0x7f060010;
        public static final int editText_worldSeed = 0x7f060011;
        public static final int View02 = 0x7f060012;
        public static final int linearLayout8 = 0x7f060013;
        public static final int textView3 = 0x7f060014;
        public static final int tableRow1 = 0x7f060015;
        public static final int ImageButton1 = 0x7f060016;
        public static final int editText1 = 0x7f060017;
        public static final int button2 = 0x7f060018;
        public static final int button1 = 0x7f060019;
        public static final int editText_options_mpusername = 0x7f06001a;
        public static final int editText_worldNameRename = 0x7f06001b;
    }
}
